### ISSUE TITLE
Make searchbar always focused

### ISSUE THREAD

**Issue by Zyten** [sattiyans/movie-series-search#6]
i.e. After completing a search, I shouldn't have to click the searchbox again

**Comment by AnshulKahar2729** [comment]
Well I can do this using javascript, assign me the issue.

**Comment by Zyten** [comment]
Sure, go ahead

**Comment by AnshulKahar2729** [comment]
Well @Zyten, it would be good if you update the repo with code which has search button in it. So that I can make an eventListener and all in it. You have just comment most of the code.

**Comment by Zyten** [comment]
You don't really need a search button for this use case actually. The search function is triggered onkeyup from the search input.

**Comment by AnshulKahar2729** [comment]
Done bro, it was super easy. There was just mistunderstanding between us. Hope you like it.
